# Generated by Django 3.2.4 on 2021-06-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=200)),
                ('subcategory', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=300)),
                ('price', models.IntegerField(default='')),
                ('pub_date', models.DateField(default='')),
                ('image', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
