# Generated by Django 3.2.4 on 2021-06-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210610_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_json',
            new_name='item_json',
        ),
    ]
