# Generated by Django 3.2.4 on 2021-06-11 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 18, 45, 35, 655435)),
        ),
    ]
